apiVersion: db.example.com/v1
kind: Postgresql
metadata:
  labels:
    app.kubernetes.io/name: p0stgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-sample
spec:
  # TODO(user): Add fields here
